name: Version bump
env: 
  ENABLE_RUN: true
  
on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ env.ENABLE_RUN }}
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git add report.txt
          git config --global user.name 'version-bump'
          git config --global user.email 'stoyan.gadev@gmail.com'
          git commit -am "Automated report"
          git push
